# Serve prerendered pages first
[[redirects]]
  from = "/aboutUs"
  to = "/aboutUs/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/contactUs"
  to = "/contactUs/index.html"
  status = 200
  force = true

# Then fallback to SPA for other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200