[[redirects]]
  from = "/contactUs"
  to = "/contactUs/index.html"
  status = 200
  force = true

  [[redirects]]
  from = "/aboutUs"
  to = "/aboutUs/index.html"
  status = 200
  force = true


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200