[[redirects]]
  from = "/aboutUs"
  to = "/aboutUs/index.html" 
  status = 200

[[redirects]]
  from = "/contactUs"
  to = "/contactUs/index.html" 
  status = 200


[[redirects]]
  from = "/*"
  to = "/index.html" 
  status = 200